In [15]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [24]:
df = pd.read_csv("datasets/Question1.csv")
df
#feature selection 
X  = df[[
    "Attendance", 
    "AssignmentCompletion", 
    "PreviousMarks",
    "MissedClasses",
    "LateSubmissions"
]]

#target selection(label)
y = df["DropoutRisk"]

#split train-test data 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

#model create -- LogisticRegression()
model = LogisticRegression()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
print(X_test)
print(y_test)
print(predictions)
accuracy = accuracy_score(y_test,predictions)
print(accuracy)

precision = precision_score(y_test,predictions)
print(precision)

recall = recall_score(y_test,predictions)
print(recall)

f1 = f1_score(y_test,predictions)
print(f1)

new_student = pd.DataFrame({
    "Attendance" : [72],
    "AssignmentCompletion" : [65],
    "PreviousMarks" : [58],
    "MissedClasses" : [4],
    "LateSubmissions" : [3]
})

prediction = model.predict(new_student)
print(prediction)



#7.no answer --------
#1. If DropoutRisk contains only two possible classes, for example:
#0 → Low/No dropout risk
#1 → High/Yes dropout risk
#then there are only two possible outcomes.


#2. Why can Logistic Regression be used here?
#Logistic Regression is commonly used when the output has two classes.


#3. Which factors seem related to higher dropout risk?
#From your selected features, we would generally expect:
#Factor	
#Low Attendance	
#Low AssignmentCompletion	
#Low PreviousMarks	
#High MissedClasses	
#High LateSubmissions	

    Attendance  AssignmentCompletion  PreviousMarks  MissedClasses  \
0           72                    65             58              4   
17          84                    80             78              2   
15          76                    70             67              3   
1           88                    82             76              1   
8           64                    58             55              6   

    LateSubmissions  
0                 3  
17                1  
15                3  
1                 1  
8                 5  
0     0
17    0
15    0
1     0
8     1
Name: DropoutRisk, dtype: int64
[1 0 0 0 1]
0.8
0.5
1.0
0.6666666666666666
[1]


In [27]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.multiclass import OneVsRestClassifier

In [40]:
df = pd.read_csv("datasets/Question2.csv")

#Feature selection
X = df[
    [
       "Attendance",
        "MathScore",
        "EnglishScore",
        "QuizScore",
        "MissedClasses"
    ]
]
y = df[
    [
        "MathSupport",
        "EnglishSupport",
        "AttendanceSupport"
    ]
]

#train_testing_split 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

model  = OneVsRestClassifier(LogisticRegression())
model.fit(X_train,y_train)

y_prediction = model.predict(X_test)
print(X_test)
print(y_test)
print(y_prediction)

new_student = pd.DataFrame({
    "Attendance" : [72],
    "MathScore" : [55],
    "EnglishScore" : [58],
    "QuizScore" : [61],
    "MissedClasses" : [1]
})

prediction = model.predict(new_student)
print(prediction)
# Display predictions in readable format
print("Student Support Prediction:")

print("Math support       :", "Yes" if prediction[0][0] == 1 else "No")
print("English support    :", "Yes" if prediction[0][1] == 1 else "No")
print("Attendance support :", "Yes" if prediction[0][2] == 1 else "No")

    Attendance  MathScore  EnglishScore  QuizScore  MissedClasses
0           72         55            58         61              1
17          89         82            79         84              1
15          77         68            66         70              2
1           91         86            84         88              0
    MathSupport  EnglishSupport  AttendanceSupport
0             0               1                  0
17            0               0                  0
15            0               0                  0
1             0               0                  0
[[1 1 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 0]]
Student Support Prediction:
Math support       : Yes
English support    : Yes
Attendance support : No


In [47]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [63]:
df = pd.read_csv("datasets/Question3.csv")

#feature_selection
X = df[
    [
        "Attendance",
        "PreviousMarks",
        "AssignmentCompletion",
        "QuizScore"	
    ]
]
y = df["Pass"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = KNeighborsClassifier(
    n_neighbors=3
)
model.fit(X_train,y_train)
predictions = model.predict(X_test)
print(X_test)
print(y_test)
print(predictions)
accuracy = accuracy_score(y_test,predictions)
print(accuracy)

precision = precision_score(y_test,predictions)
print(precision)

recall = recall_score(y_test,predictions)
print(recall)

f1 = f1_score(y_test,predictions)
print(f1)

new_student = pd.DataFrame({
    "Attendance" : [91],
     "PreviousMarks" : [84],
    "AssignmentCompletion" : [86],
    "QuizScore" : [88]
})
prediction = model.predict(new_student)
print(prediction)

new_student_scaled = scaler.transform(new_student)


# Find the 3 nearest students
distances, indices = model.kneighbors(
    new_student_scaled,
    n_neighbors=3
)


# Display the 3 nearest students
print("3 Nearest Students:")

for i in range(3):
    student_index = indices[0][i]

    print(f"\nStudent {i+1}:")
    print(X_train.iloc[student_index])
    print("Pass:", y_train.iloc[student_index])
    print("Distance:", distances[0][i])


    Attendance  PreviousMarks  AssignmentCompletion  QuizScore
0           72             58                    65         61
17          89             79                    82         84
15          77             66                    68         71
1           91             84                    86         88
0     0
17    1
15    1
1     1
Name: Pass, dtype: int64
[0 1 1 1]
1.0
1.0
1.0
1.0
[1]
3 Nearest Students:

Student 1:
Attendance              60
PreviousMarks           43
AssignmentCompletion    41
QuizScore               48
Name: 16, dtype: int64
Pass: 0
Distance: 94.9569784223377

Student 2:
Attendance              62
PreviousMarks           45
AssignmentCompletion    48
QuizScore               50
Name: 6, dtype: int64
Pass: 0
Distance: 101.13057623328098

Student 3:
Attendance              65
PreviousMarks           49
AssignmentCompletion    45
QuizScore               52
Name: 11, dtype: int64
Pass: 0
Distance: 104.38486323696826


D:\LearningPythonAIUdaanSeries\myvenv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
