In [59]:
import pandas as pd
import numpy as np

In [78]:
df = pd.read_csv("datasets/daraz_dataset.csv")
df.head()
df.shape
df.columns
df.dtypes
df["Age"]
df["Age"] = pd.to_numeric(df["Age"],errors="coerce")

numeric_columns = [
"Age",
"Quantity",
"UnitPrice",
"DiscountPercent",
"TotalAmount",
"Rating"
]
for column in numeric_columns:
    df[column] = pd.to_numeric(df[column],errors="coerce")


df.isnull().sum()
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].mean())

features = ["Age", "Quantity", "UnitPrice", "DiscountPercent"]
target = "TotalAmount"

#Super features store garne X, target store garne Y banaunu
X = df[features]
y = df[target]

type(X)
type(y)

X = X.to_numpy()
y = y.to_numpy()

type(X)
type(y)

# X.shape
# X.ndim
# X.dtype
# X.nbytes
X[0]
X[:,0]
X[:,3]
print(X[X[:,0]>30])
print(np.min(X[:,0]))
df
    

[[   52     2 33418    20]
 [   31     2 46053    15]
 [   42     5 17635     0]
 ...
 [   39     4 30055    20]
 [   48     3 47942    20]
 [   35     4  5707     5]]
18


,OrderID,OrderDate,CustomerName,Age,Gender,District,Category,Product,Quantity,UnitPrice,DiscountPercent,TotalAmount,PaymentMethod,Rating,OrderStatus
0,DZ100001,2026-03-04,Anita Basnet,24,Male,Nepalgunj,Sports,Football,1,48898,10,44008.20,IME Pay,1,Delivered
1,DZ100002,2026-01-07,Pooja Basnet,52,Female,Pokhara,Electronics,Bluetooth Speaker,2,33418,20,53468.80,IME Pay,5,Cancelled
2,DZ100003,2026-03-29,Rohit Basnet,31,Female,Lalitpur,Books,Python Basics,2,46053,15,78290.10,eSewa,4,Delivered
3,DZ100004,2026-04-28,Pooja Sharma,42,Male,Chitwan,Home,Chair,5,17635,0,88175.00,COD,5,Cancelled
4,DZ100005,2026-03-16,Ram Adhikari,32,Male,Dharan,Groceries,Tea,1,3303,5,3137.85,COD,4,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,DZ100496,2026-03-08,Sita Thapa,48,Male,Nepalgunj,Electronics,Smart Watch,3,47942,20,115060.80,eSewa,3,Processing
496,DZ100497,2026-05-10,Ram Adhikari,35,Female,Bhaktapur,Electronics,Power Bank,4,5707,5,21686.60,Card,3,Cancelled
497,DZ100498,2026-06-04,Nabin Shrestha,27,Female,Itahari,Books,Data Science 101,1,48890,0,48890.00,Khalti,3,Shipped
498,DZ100499,2026-01-22,Gita Shrestha,27,Female,Dharan,Beauty,Shampoo,5,2468,10,11106.00,IME Pay,2,Returned


In [73]:
age = np.array([10,20,30])
roll_no = np.array([11,22,33])
print(age)
print(roll_no)
type(age)
students = np.array([
    [20,30,40],
    [10,12,14]
])
print(students)

[10 20 30]
[11 22 33]
[[20 30 40]
 [10 12 14]]


In [77]:
student_datas = np.array([[12,90],
[14,80],
                           [16,50]
                          ])
print(students_datas)
weights = np.array([
    [10],
    [2]]
                  )
prediction = np.dot(student_datas,weights)
print(prediction)

[[12 90]
 [14 80]
 [16 50]]
[[300]
 [300]
 [260]]
